import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Facebook, Instagram, Leaf, MapPin, Menu, MessageCircle, Ruler, ShieldCheck, Snowflake, Star, X } from 'lucide-react';
import { useListApprovedReviews, useListProducts, useSubmitReview } from '@workspace/api-client-react';
import type { Product, Review } from '@workspace/api-client-react';
import { BUSINESS_NAME, openWhatsAppEnquiry } from '@/lib/brand';

const categories = ['All', 'Footwear', 'Outerwear', 'Accessories'] as const;
type Category = (typeof categories)[number];

const processSteps = [
  ['01', 'A useful beginning', 'We start with your place, your weather, and how you move through a day. A short conversation is the first measurement.', MapPin],
  ['02', 'Materials with a story', 'Hide, wool, lining, and hardware are selected with care. We share what is available before anything is cut.', Leaf],
  ['03', 'Cut by hand', 'Patterns are adjusted for your proportions and use. Every seam, edge, and tie is handled slowly at the studio table.', Ruler],
  ['04', 'Ready for real weather', 'We finish, check, and photograph the piece before it travels. Shipping and care notes are confirmed with you directly.', ShieldCheck],
] as const;

function useReveal() {
  useEffect(() => {
    const elements = Array.from(document.querySelectorAll<HTMLElement>('.reveal'));
    if (!('IntersectionObserver' in window)) {
      elements.forEach((element) => element.classList.add('is-visible'));
      return;
    }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        observer.unobserve(entry.target);
      }
    }), { rootMargin: '0px 0px -8% 0px', threshold: 0.08 });
    elements.forEach((element) => observer.observe(element));
    return () => observer.disconnect();
  }, []);
}

function ImageFrame({ src, alt, className = '' }: { src?: string; alt: string; className?: string }) {
  return (
    <div className={`image-zoom overflow-hidden bg-[hsl(var(--muted))] ${className}`}>
      {src ? <img src={src} alt={alt} className="h-full w-full object-cover" loading="lazy" /> : <div className="flex h-full items-end p-6"><span className="font-display text-3xl text-[hsl(var(--primary)/.42)]">Image coming soon</span></div>}
    </div>
  );
}

function SiteNav({ onEnquire }: { onEnquire: () => void }) {
  const [open, setOpen] = useState(false);
  const links = [['Collection', '#collection'], ['The studio', '#studio'], ['Our process', '#process'], ['Reviews', '#reviews']];
  return (
    <header className="absolute inset-x-0 top-0 z-30">
      <div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-8 lg:px-14 lg:py-7">
        <a href="#top" onClick={() => setOpen(false)} className="focus-ring flex items-center gap-3 text-[hsl(var(--card))]" data-testid="link-brand">
          <span className="flex h-9 w-9 items-center justify-center rounded-full border border-[hsl(var(--secondary)/.7)] text-[hsl(var(--secondary))]"><Snowflake size={16} strokeWidth={1.4} /></span>
           <span className="leading-[0.9]"><span className="block font-display text-xl font-semibold tracking-[0.03em]">Leather &amp;</span><span className="block text-[9px] font-bold uppercase tracking-[0.2em] text-[hsl(var(--card)/.72)]">Sealskin Creations</span></span>
        </a>
        <nav className="hidden items-center gap-7 md:flex" aria-label="Main navigation">
          {links.map(([label, href]) => <a key={href} href={href} className="focus-ring text-[11px] font-semibold uppercase tracking-[0.14em] text-[hsl(var(--card)/.78)] transition-colors hover:text-[hsl(var(--secondary))]" data-testid={`link-nav-${label.toLowerCase().replace(/\s+/g, '-')}`}>{label}</a>)}
        </nav>
        <button type="button" onClick={onEnquire} className="focus-ring hidden items-center gap-2 rounded-full border border-[hsl(var(--secondary)/.75)] px-4 py-2.5 text-[10px] font-bold uppercase tracking-[0.14em] text-[hsl(var(--card))] transition-colors hover:bg-[hsl(var(--secondary))] hover:text-[hsl(var(--primary))] md:flex" data-testid="button-nav-enquire">Start a conversation <ArrowUpRight size={14} /></button>
        <button type="button" onClick={() => setOpen((current) => !current)} className="focus-ring rounded-full border border-[hsl(var(--card)/.3)] p-2 text-[hsl(var(--card))] md:hidden" aria-expanded={open} aria-label={open ? 'Close navigation' : 'Open navigation'} data-testid="button-mobile-menu">{open ? <X size={20} /> : <Menu size={20} />}</button>
      </div>
      {open && <div className="mx-4 rounded-2xl border border-[hsl(var(--card)/.16)] bg-[hsl(var(--primary)/.96)] p-5 shadow-2xl md:hidden"><nav className="flex flex-col gap-5" aria-label="Mobile navigation">
        {links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="focus-ring border-b border-[hsl(var(--card)/.12)] pb-4 text-sm font-semibold text-[hsl(var(--card))]" data-testid={`link-mobile-${label.toLowerCase().replace(/\s+/g, '-')}`}>{label}</a>)}
        <button type="button" onClick={() => { setOpen(false); onEnquire(); }} className="flex items-center justify-between rounded-xl bg-[hsl(var(--secondary))] px-4 py-3 text-left text-xs font-bold uppercase tracking-[0.14em] text-[hsl(var(--primary))]" data-testid="button-mobile-enquire">Start a conversation <ArrowUpRight size={16} /></button>
      </nav></div>}
    </header>
  );
}

function ProductCard({ product, index }: { product: Product; index: number }) {
  return (
    <article className={`reveal reveal-delay-${Math.min(index + 1, 3)} group`} data-testid={`card-product-${product.id}`}>
      <div className={`relative mb-5 overflow-hidden bg-[hsl(var(--muted))] ${index % 3 === 1 ? 'aspect-[3/4]' : index % 3 === 2 ? 'aspect-[5/6]' : 'aspect-[4/5]'}`}>
        <ImageFrame src={product.imageUrl} alt={product.name} className="h-full w-full" />
        <span className="absolute left-4 top-4 bg-[hsl(var(--card)/.92)] px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.17em] text-[hsl(var(--primary))]">{product.category}</span>
        {!product.available && <span className="absolute right-4 top-4 bg-[hsl(var(--primary)/.9)] px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.17em] text-[hsl(var(--card))]">Made to order</span>}
        <button type="button" onClick={() => openWhatsAppEnquiry(product.name)} className="focus-ring absolute bottom-4 right-4 flex translate-y-2 items-center gap-2 rounded-full bg-[hsl(var(--secondary))] px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-[0.13em] text-[hsl(var(--primary))] opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100 max-sm:translate-y-0 max-sm:opacity-100" data-testid={`button-order-whatsapp-${product.id}`}>Order on WhatsApp <ArrowUpRight size={14} /></button>
      </div>
      <div className="flex items-start justify-between gap-4">
        <div><h3 className="font-display text-3xl font-semibold leading-none text-[hsl(var(--primary))]">{product.name}</h3><p className="mt-2 max-w-[280px] text-sm leading-6 text-[hsl(var(--muted-foreground))]">{product.description}</p></div>
        <button type="button" onClick={() => openWhatsAppEnquiry(product.name)} className="focus-ring mt-1 shrink-0 rounded-full border border-[hsl(var(--primary)/.22)] p-2.5 text-[hsl(var(--primary))] transition-colors hover:border-[hsl(var(--secondary))] hover:bg-[hsl(var(--secondary))]" aria-label={`Order ${product.name} on WhatsApp`} data-testid={`button-product-arrow-${product.id}`}><ArrowUpRight size={16} /></button>
      </div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[hsl(var(--border))] pt-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-[hsl(var(--muted-foreground))]"><span>{product.material || product.detail}</span><span>{product.season}</span></div>
    </article>
  );
}

function Reviews() {
  const reviewsQuery = useListApprovedReviews();
  const submitReview = useSubmitReview();
  const [form, setForm] = useState({ displayName: '', rating: 5, body: '' });
  const [message, setMessage] = useState('');
  const reviews = reviewsQuery.data ?? [];
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!form.displayName.trim() || !form.body.trim()) return;
    submitReview.mutate({ data: { displayName: form.displayName.trim(), rating: form.rating, body: form.body.trim() } }, {
      onSuccess: () => { setForm({ displayName: '', rating: 5, body: '' }); setMessage('Thank you. Your review is now awaiting owner approval.'); },
      onError: () => setMessage('We could not send that review. Please try again.'),
    });
  };
  return (
    <section id="reviews" className="scroll-mt-10 bg-[hsl(var(--background))] px-5 py-24 sm:px-8 sm:py-32 lg:px-14">
      <div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[.72fr_1.28fr]">
        <div className="reveal"><p className="eyebrow text-[hsl(var(--accent))]">Notes from the field</p><h2 className="mt-5 max-w-[430px] font-display text-[clamp(3rem,5vw,5.7rem)] font-semibold leading-[.86] tracking-[-.04em] text-[hsl(var(--primary))]">Worn, lived in, remembered.</h2><p className="mt-7 max-w-[360px] text-sm leading-7 text-[hsl(var(--muted-foreground))]">Customer notes are shared with permission and reviewed before they appear here.</p></div>
        <div>
          {reviewsQuery.isLoading && <div className="grid gap-4 sm:grid-cols-2" aria-label="Loading reviews"><div className="skeleton h-48" /><div className="skeleton h-48" /></div>}
          {reviewsQuery.isError && <div className="border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-7 text-sm text-[hsl(var(--muted-foreground))]" data-testid="state-reviews-error">Reviews are taking a moment to load. Please refresh and try again.</div>}
          {!reviewsQuery.isLoading && !reviewsQuery.isError && reviews.length === 0 && <div className="border border-dashed border-[hsl(var(--border))] p-8 text-sm text-[hsl(var(--muted-foreground))]" data-testid="state-reviews-empty">The first field note is still to come.</div>}
          <div className="grid gap-4 sm:grid-cols-2">{reviews.map((review: Review, index: number) => <article key={review.id} className={`reveal reveal-delay-${Math.min(index + 1, 3)} border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-7`} data-testid={`card-review-${review.id}`}><div className="flex items-center gap-1 text-[hsl(var(--secondary))]" aria-label={`${review.rating} out of 5 stars`}>{Array.from({ length: 5 }).map((_, star) => <Star key={star} size={14} fill={star < review.rating ? 'currentColor' : 'none'} />)}</div><p className="mt-5 font-display text-2xl leading-[1.05] text-[hsl(var(--primary))]">“{review.body}”</p><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.16em] text-[hsl(var(--accent))]">{review.displayName}</p></article>)}</div>
          <form onSubmit={submit} className="mt-8 border-t border-[hsl(var(--border))] pt-8" data-testid="form-submit-review"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow text-[hsl(var(--accent))]">Leave a note</p><h3 className="mt-2 font-display text-3xl text-[hsl(var(--primary))]">Tell us how it settles in.</h3></div><span className="hidden text-[10px] uppercase tracking-[0.12em] text-[hsl(var(--muted-foreground))] sm:block">Owner approval required</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase tracking-[0.13em] text-[hsl(var(--muted-foreground))]">Name<input required value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} className="field mt-2" placeholder="Your name" data-testid="input-review-name" /></label><div><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[hsl(var(--muted-foreground))]">Rating</span><div className="mt-2 flex gap-2">{[1, 2, 3, 4, 5].map((rating) => <button key={rating} type="button" onClick={() => setForm({ ...form, rating })} className={`focus-ring rounded-full border p-2 ${rating <= form.rating ? 'border-[hsl(var(--secondary))] bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]' : 'border-[hsl(var(--border))] text-[hsl(var(--muted-foreground))]'}`} aria-label={`Rate ${rating} out of 5`} aria-pressed={rating === form.rating} data-testid={`button-rating-${rating}`}><Star size={15} fill={rating <= form.rating ? 'currentColor' : 'none'} /></button>)}</div></div></div><label className="mt-4 block text-[10px] font-bold uppercase tracking-[0.13em] text-[hsl(var(--muted-foreground))]">Comment<textarea required value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} className="field mt-2 min-h-28 resize-y" placeholder="A few words about your piece..." data-testid="textarea-review-comment" /></label><div className="mt-5 flex flex-wrap items-center gap-5"><button type="submit" disabled={submitReview.isPending} className="focus-ring rounded-full bg-[hsl(var(--primary))] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.15em] text-[hsl(var(--card))] disabled:opacity-50" data-testid="button-submit-review">{submitReview.isPending ? 'Sending note…' : 'Send for approval'}</button>{message && <p className="text-xs text-[hsl(var(--accent))]" role="status" data-testid="status-review">{message}</p>}</div></form>
        </div>
      </div>
    </section>
  );
}

export default function Home() {
  const productsQuery = useListProducts();
  const [activeCategory, setActiveCategory] = useState<Category>('All');
  useReveal();
   useEffect(() => { document.title = `${BUSINESS_NAME} — Hand-sewn mukluks, parkas & slippers`; }, []);
  const products = productsQuery.data ?? [];
  const filteredProducts = useMemo(() => activeCategory === 'All' ? products : products.filter((product) => product.category === activeCategory), [activeCategory, products]);
  const heroImage = products[0]?.imageUrl;
  return (
    <main id="top" className="min-h-[100dvh] overflow-hidden bg-[hsl(var(--background))]">
      <section className="texture-noise relative isolate min-h-[710px] overflow-hidden bg-[hsl(var(--primary))] text-[hsl(var(--card))] sm:min-h-[780px]">
        <div className="absolute inset-0 -z-20 bg-[linear-gradient(90deg,rgba(18,34,43,.94)_0%,rgba(18,34,43,.74)_48%,rgba(18,34,43,.22)_100%)]" /><ImageFrame src={heroImage} alt="A Heritage Skinwear Studio product" className="absolute inset-0 -z-30 h-full w-full opacity-80 mix-blend-luminosity" /><div className="absolute -right-24 top-44 -z-10 h-[420px] w-[420px] rounded-full border border-[hsl(var(--secondary)/.28)] sm:right-[-80px] sm:h-[560px] sm:w-[560px]" /><SiteNav onEnquire={() => openWhatsAppEnquiry()} />
        <div className="mx-auto flex min-h-[710px] max-w-[1440px] items-end px-5 pb-14 pt-36 sm:min-h-[780px] sm:px-8 sm:pb-20 lg:px-14"><div className="relative z-10 max-w-[760px]"><p className="reveal eyebrow mb-7 flex items-center gap-3 text-[hsl(var(--secondary))]"><span className="h-px w-8 bg-[hsl(var(--secondary))]" /> Hand-sewn hide goods · made for the long season</p><h1 className="reveal reveal-delay-1 max-w-[760px] font-display text-[clamp(4.4rem,10vw,9.6rem)] font-semibold leading-[.79] tracking-[-.045em] text-[hsl(var(--card))]">Made for<br /><span className="ml-[.7em] text-[hsl(var(--secondary))]">the long</span><br />season.</h1><div className="reveal reveal-delay-2 mt-9 flex max-w-[580px] flex-col gap-7 sm:ml-[10%] sm:flex-row sm:items-end sm:gap-10"><p className="max-w-[350px] text-sm leading-7 text-[hsl(var(--card)/.72)]">Authentic customized hand-sewn mukluks, parkas, slippers, and hide goods from a small northern studio. Start with a question; we will talk through what is possible.</p><a href="#collection" className="focus-ring inline-flex shrink-0 items-center gap-3 text-[11px] font-bold uppercase tracking-[0.17em] text-[hsl(var(--card))] hover:text-[hsl(var(--secondary))]" data-testid="link-hero-collection">Explore the collection <span className="flex h-10 w-10 items-center justify-center rounded-full border border-[hsl(var(--secondary)/.7)]"><ArrowDown size={15} /></span></a></div></div></div>
      </section>
      <div className="overflow-hidden border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary))] py-3.5 text-[hsl(var(--primary))]"><div className="flex min-w-max animate-[marquee_26s_linear_infinite] items-center gap-9 text-[10px] font-bold uppercase tracking-[0.2em]">{['Made with respect', 'Small-batch by hand', 'Cold-region ready', 'Custom conversations', 'Made with respect', 'Small-batch by hand', 'Cold-region ready'].map((item, index) => <span key={`${item}-${index}`} className="flex items-center gap-9"><span>{item}</span><span className="text-[hsl(var(--accent))]">·</span></span>)}</div></div>
      <section className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 sm:py-32 lg:px-14"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div className="reveal"><p className="eyebrow text-[hsl(var(--accent))]">A considered layer</p><div className="mt-6 h-px w-20 bg-[hsl(var(--accent))]" /></div><div className="reveal reveal-delay-1"><h2 className="max-w-[850px] font-display text-[clamp(2.8rem,5.4vw,5.8rem)] font-semibold leading-[.92] tracking-[-.035em] text-[hsl(var(--primary))]">The north asks for clothing that does more than look the part.</h2><p className="mt-8 max-w-[640px] text-base leading-8 text-[hsl(var(--muted-foreground))]">Leather, sealskin, hide, wool, and careful hand-sewn construction come together in practical pieces made for real use. We work respectfully and do not claim to speak for a specific nation or tradition.</p><a href="#studio" className="focus-ring mt-8 inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.15em] text-[hsl(var(--accent))]" data-testid="link-intro-studio">Meet the maker <ArrowRight size={15} /></a></div></div></section>
      <section id="collection" className="scroll-mt-10 bg-[hsl(var(--card))] px-5 py-24 sm:px-8 sm:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="reveal flex flex-col justify-between gap-7 border-b border-[hsl(var(--border))] pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-[hsl(var(--accent))]">The current collection</p><h2 className="mt-3 font-display text-5xl font-semibold tracking-[-.03em] text-[hsl(var(--primary))] sm:text-7xl">Pieces with a pulse.</h2></div><p className="max-w-[300px] text-sm leading-6 text-[hsl(var(--muted-foreground))]">Availability, materials, sizing, pricing, and shipping are confirmed in conversation.</p></div><div className="reveal reveal-delay-1 mt-7 flex flex-wrap gap-2" role="tablist" aria-label="Filter collection">{categories.map((category) => <button type="button" key={category} onClick={() => setActiveCategory(category)} role="tab" aria-selected={activeCategory === category} className={`focus-ring rounded-full border px-4 py-2 text-[10px] font-bold uppercase tracking-[0.15em] transition-colors ${activeCategory === category ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary))] text-[hsl(var(--card))]' : 'border-[hsl(var(--border))] text-[hsl(var(--muted-foreground))] hover:border-[hsl(var(--primary)/.5)] hover:text-[hsl(var(--primary))]'}`} data-testid={`button-filter-${category.toLowerCase()}`}>{category}</button>)}</div>{productsQuery.isLoading && <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="skeleton aspect-[4/5]" />)}</div>}{productsQuery.isError && <div className="mt-12 border border-[hsl(var(--border))] p-8 text-sm text-[hsl(var(--muted-foreground))]" data-testid="state-products-error">The collection could not be loaded. Please try again shortly.</div>}{!productsQuery.isLoading && !productsQuery.isError && filteredProducts.length === 0 && <div className="mt-12 border border-dashed border-[hsl(var(--border))] p-12 text-center" data-testid="state-products-empty"><p className="font-display text-3xl text-[hsl(var(--primary))]">The table is between pieces.</p><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">Check back soon or start a custom conversation.</p></div>}<div className="mt-12 grid gap-x-6 gap-y-16 sm:grid-cols-2 lg:grid-cols-4">{filteredProducts.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div></div></section>
      <section className="bg-[hsl(var(--primary))] px-5 py-24 text-[hsl(var(--card))] sm:px-8 sm:py-32 lg:px-14"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div className="reveal relative min-h-[480px] overflow-hidden bg-[hsl(var(--accent))] sm:min-h-[620px]"><ImageFrame src={products[1]?.imageUrl || products[0]?.imageUrl} alt="A hand-sewn cold weather piece" className="h-full w-full opacity-90 mix-blend-luminosity" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[hsl(var(--primary)/.85)] to-transparent p-7 pt-28"><p className="eyebrow text-[hsl(var(--secondary))]">Field note / 01</p><p className="mt-2 max-w-[220px] font-display text-3xl leading-none">Soft where it should be. Steady where it matters.</p></div></div><div className="flex flex-col justify-center"><p className="reveal eyebrow text-[hsl(var(--secondary))]">The story in the making</p><h2 className="reveal reveal-delay-1 mt-5 max-w-[700px] font-display text-[clamp(3rem,6vw,6.5rem)] font-semibold leading-[.84] tracking-[-.04em]">A good piece<br /><span className="text-[hsl(var(--secondary))]">settles in.</span></h2><p className="reveal reveal-delay-2 mt-9 max-w-[530px] text-base leading-8 text-[hsl(var(--card)/.68)]">You feel it in the first walk: the balance of a mukluk, the give of a slipper, the way a parka leaves room for a sweater and a full breath. Our forms are simple on purpose, then made specific to the person wearing them.</p><div className="reveal reveal-delay-3 mt-10 grid max-w-[520px] grid-cols-2 gap-6 border-t border-[hsl(var(--card)/.18)] pt-6 sm:grid-cols-3">{[['01', 'Quiet silhouette'], ['02', 'Useful warmth'], ['03', 'Your proportions']].map(([number, label]) => <div key={number}><p className="font-display text-4xl text-[hsl(var(--secondary))]">{number}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[hsl(var(--card)/.55)]">{label}</p></div>)}</div></div></div></section>
      <section id="process" className="scroll-mt-10 px-5 py-24 sm:px-8 sm:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="reveal grid gap-8 border-b border-[hsl(var(--border))] pb-10 lg:grid-cols-[.65fr_1.35fr]"><p className="eyebrow text-[hsl(var(--accent))]">How it comes together</p><div><h2 className="max-w-[720px] font-display text-[clamp(3rem,5.5vw,6rem)] font-semibold leading-[.87] tracking-[-.04em] text-[hsl(var(--primary))]">Slow is a material choice.</h2><p className="mt-7 max-w-[530px] text-base leading-8 text-[hsl(var(--muted-foreground))]">The work stays small so the decisions can stay close. Here is what a custom conversation looks like from our side of the table.</p></div></div><div className="grid divide-y divide-[hsl(var(--border))] md:grid-cols-4 md:divide-x md:divide-y-0">{processSteps.map(([number, title, body, Icon], index) => <div key={number} className={`reveal reveal-delay-${Math.min(index + 1, 3)} p-0 py-9 md:px-7 md:py-10`} data-testid={`process-step-${number}`}><div className="flex items-center justify-between"><span className="font-display text-4xl text-[hsl(var(--accent))]">{number}</span><Icon size={21} strokeWidth={1.3} className="text-[hsl(var(--accent))]" /></div><h3 className="mt-11 font-display text-3xl font-semibold leading-none text-[hsl(var(--primary))]">{title}</h3><p className="mt-4 text-sm leading-7 text-[hsl(var(--muted-foreground))]">{body}</p></div>)}</div></div></section>
      <section id="studio" className="scroll-mt-10 bg-[hsl(var(--muted)/.68)] px-5 py-24 sm:px-8 sm:py-32 lg:px-14"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-24"><div className="reveal"><p className="eyebrow text-[hsl(var(--accent))]">About the studio</p><h2 className="mt-5 max-w-[680px] font-display text-[clamp(3.2rem,6vw,6.8rem)] font-semibold leading-[.83] tracking-[-.04em] text-[hsl(var(--primary))]">A small room.<br />A wide north.</h2><p className="mt-9 max-w-[580px] text-base leading-8 text-[hsl(var(--muted-foreground))]">Heritage Skinwear Studio is a one-maker practice shaped by long winters, practical beauty, and a deep respect for the work that came before us. We make northern-inspired pieces without pretending to speak for a specific nation or tradition.</p><button type="button" onClick={() => openWhatsAppEnquiry()} className="focus-ring mt-9 inline-flex items-center gap-3 border-b border-[hsl(var(--accent))] pb-2 text-[11px] font-bold uppercase tracking-[0.15em] text-[hsl(var(--primary))]" data-testid="button-studio-enquire">Talk with the maker <ArrowUpRight size={15} /></button></div><div className="reveal reveal-delay-1 relative"><ImageFrame src={products[2]?.imageUrl || products[0]?.imageUrl} alt="Materials and a hand-sewn piece in the studio" className="relative aspect-[4/5] w-[88%] bg-[hsl(var(--accent))]" /><div className="absolute -right-1 bottom-8 flex w-[45%] items-center gap-3 bg-[hsl(var(--primary))] px-4 py-4 text-[hsl(var(--card))] sm:-right-5 sm:bottom-12 sm:px-6"><Snowflake size={22} strokeWidth={1.2} className="text-[hsl(var(--secondary))]" /><span className="text-[10px] font-bold uppercase leading-4 tracking-[0.14em]">Made north<br />of the 60th</span></div></div></div></section>
      <Reviews />
      <section className="relative overflow-hidden bg-[hsl(var(--accent))] px-5 py-24 text-[hsl(var(--card))] sm:px-8 sm:py-32 lg:px-14"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div className="reveal"><MessageCircle size={30} strokeWidth={1.2} className="text-[hsl(var(--secondary))]" /><p className="mt-8 max-w-[260px] font-display text-4xl leading-[.95] sm:text-5xl">“The best pieces become part of the weather.”</p><p className="mt-7 text-[10px] font-bold uppercase tracking-[0.18em] text-[hsl(var(--card)/.65)]">A studio principle</p></div><div className="reveal reveal-delay-1 relative z-10"><p className="eyebrow text-[hsl(var(--secondary))]">Bring a question, not a shopping list</p><h2 className="mt-5 max-w-[780px] font-display text-[clamp(3.4rem,6.8vw,7.4rem)] font-semibold leading-[.8] tracking-[-.045em]">Let’s find<br /><span className="text-[hsl(var(--secondary))]">your layer.</span></h2><p className="mt-9 max-w-[510px] text-base leading-8 text-[hsl(var(--card)/.72)]">Send a note on WhatsApp and tell us where you are, what you need, and what caught your eye.</p><button type="button" onClick={() => openWhatsAppEnquiry()} className="focus-ring mt-9 inline-flex items-center gap-3 rounded-full bg-[hsl(var(--secondary))] px-6 py-4 text-[11px] font-bold uppercase tracking-[0.15em] text-[hsl(var(--primary))]" data-testid="button-final-enquire">Open WhatsApp enquiry <ArrowUpRight size={17} /></button></div></div></section>
       <footer className="bg-[hsl(var(--primary))] px-5 pb-8 pt-12 text-[hsl(var(--card))] sm:px-8 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-10 border-b border-[hsl(var(--card)/.16)] pb-10 md:flex-row md:items-end"><div><a href="#top" className="focus-ring inline-flex items-center gap-3" data-testid="link-footer-brand"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[hsl(var(--secondary)/.7)] text-[hsl(var(--secondary))]"><Snowflake size={17} strokeWidth={1.4} /></span><span><span className="block font-display text-2xl font-semibold leading-none">Leather &amp;</span><span className="mt-1 block text-[9px] font-bold uppercase tracking-[0.2em] text-[hsl(var(--card)/.62)]">Sealskin Creations</span></span></a><p className="mt-5 max-w-[300px] text-xs leading-6 text-[hsl(var(--card)/.5)]">Hand-sewn leather, sealskin, hide, and winter goods made with care and a direct line to the maker.</p></div><div className="flex gap-4"><a href="https://www.instagram.com" target="_blank" rel="noreferrer" className="focus-ring rounded-full border border-[hsl(var(--card)/.2)] p-3 text-[hsl(var(--card)/.72)]" aria-label="Instagram" data-testid="link-instagram"><Instagram size={17} /></a><a href="https://www.facebook.com" target="_blank" rel="noreferrer" className="focus-ring rounded-full border border-[hsl(var(--card)/.2)] p-3 text-[hsl(var(--card)/.72)]" aria-label="Facebook" data-testid="link-facebook"><Facebook size={17} /></a><button type="button" onClick={() => openWhatsAppEnquiry()} className="focus-ring flex items-center gap-2 rounded-full border border-[hsl(var(--secondary)/.7)] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.13em] text-[hsl(var(--secondary))]" data-testid="button-footer-enquire">WhatsApp <ArrowUpRight size={14} /></button></div></div><div className="flex flex-col justify-between gap-3 pt-6 text-[9px] font-semibold uppercase tracking-[0.15em] text-[hsl(var(--card)/.38)] sm:flex-row"><span>© {new Date().getFullYear()} {BUSINESS_NAME}</span><span>Hand-sewn goods · Canada &amp; beyond</span></div></div></footer>
    </main>
  );
}